/* CVS $Id: $ */
 package com;
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from C:\Users\NiMo3\IdeaProjects\testRabbit\netflow_text.owl 
 * @author Auto-generated by schemagen on 29 May 2018 15:24 
 */
public class NetFlowOnt {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Property asDst = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/asDst" );
    
    public static final Property asPath = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/asPath" );
    
    public static final Property asSrc = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/asSrc" );
    
    public static final Property bytes = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/bytes" );
    
    public static final Property eventType = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/eventType" );
    
    public static final Property ipDst = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/ipDst" );
    
    public static final Property ipProto = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/ipProto" );
    
    public static final Property ipSrc = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/ipSrc" );
    
    public static final Property localPref = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/localPref" );
    
    public static final Property med = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/med" );
    
    public static final Property packets = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/packets" );
    
    public static final Property peerAsDst = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/peerAsDst" );
    
    public static final Property portDst = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/portDst" );
    
    public static final Property portSrc = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/portSrc" );
    
    public static final Property stampInserted = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/stampInserted" );
    
    public static final Property stampUpdated = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/stampUpdated" );
    
    public static final Property tos = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/tos" );
    
    public static final Property writerId = M_MODEL.createProperty( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/writerId" );
    
    public static final Resource asn = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/asn" );
    
    public static final Resource ipv4 = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/ipv4" );
    
    public static final Resource ipv6 = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/ipv6" );
    
    public static final Resource netflow = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/netflow" );
    
    public static final Resource port = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/port" );
    
    public static final Resource protocol = M_MODEL.createResource( "http://www.semanticweb.org/nimo3/ontologies/2018/4/netflow_test/protocol" );
    
}
